FROM ubuntu:24.04 AS base

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# install build tools(alphabetic order)
RUN apt update && apt install -y \
    autoconf2.69 \
    bash-completion \
    bison \
    bzip2 \
    ca-certificates \
    ccache \
    clangd \
    cmake \
    cpanminus \
    cron \
    curl \
    docbook-xml \
    docbook-xsl \
    flex \
    fswatch \
    g++-14 \
    gcc-14 \
    gdb \
    git \
    htop \
    iproute2 \
    libclang-dev \
    libcurl4-gnutls-dev \
    libgdal-dev \
    libgeos-dev \
    libicu-dev \
    libkrb5-dev \
    liblz4-dev \
    libpam0g-dev \
    libperl-dev \
    libpq-dev \
    libproj-dev \
    libprotobuf-c-dev \
    libreadline-dev \
    libselinux1-dev \
    libssl-dev \
    libxml2-dev \
    libxml2-utils \
    libxslt-dev \
    libzstd-dev \
    locales \
    lsb-release \
    lsof \
    make \
    man \
    meson \
    net-tools \
    neovim \
    ninja-build \
    perl \
    pkg-config \
    procps \
    protobuf-c-compiler \
    pspg \
    python3 \
    python3-pip \
    python3.12 \
    python3.12-venv \
    stow \
    strace \
    sudo \
    tmux \
    tree \
    unzip \
    uuid-dev \
    valgrind \
    wget \
    xsltproc \
    zlib1g-dev \
 && apt autoremove -y \
 && apt clean \
 && rm -rf /var/lib/apt/lists/*

RUN sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 \
 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100 \
 && sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-14 100 \
 && sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-14 100

RUN sudo pip3 install --break-system-packages pipenv pipenv-shebang

RUN cpanm install IPC::Run
RUN cpanm https://cpan.metacpan.org/authors/id/S/SH/SHANCOCK/Perl-Tidy-20230309.tar.gz

RUN locale-gen en_US.UTF-8

# add the iceberg user to sudoers and allow all sudoers to login without a password prompt
RUN useradd -ms /bin/bash iceberg \
 && usermod -aG sudo iceberg \
 && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

WORKDIR /home/iceberg
USER iceberg

# run all make commands with the number of cores available
RUN echo "export MAKEFLAGS=\"-j \$(nproc)\"" >> "/home/iceberg/.bashrc"

RUN git clone --branch v1.4.3 --depth 1 https://github.com/theory/pgenv.git .pgenv
ENV PATH="/home/iceberg/.pgenv/bin:${PATH}"
ENV PATH="/home/iceberg/.pgenv/pgsql/bin:${PATH}"

# build postgres versions separately for effective parrallelism and caching of already built
# versions when changing only certain versions
FROM base AS pg18
RUN MAKEFLAGS="-j $(nproc)" pgenv build 18.4
RUN rm .pgenv/src/*.tar*
RUN make -C .pgenv/src/postgresql-*/ clean
RUN make -C .pgenv/src/postgresql-*/src/include install

# Stage the pgenv artifacts for PG18
RUN mkdir .pgenv-staging/
RUN cp -r .pgenv/src .pgenv/pgsql-* .pgenv/config .pgenv-staging/
RUN rm -f .pgenv-staging/config/default.conf

FROM base AS uncrustify-builder

RUN sudo apt update && sudo apt install -y cmake tree

WORKDIR /uncrustify
RUN curl -L https://github.com/uncrustify/uncrustify/archive/uncrustify-0.82.0.tar.gz | tar xz
WORKDIR /uncrustify/uncrustify-uncrustify-0.82.0/
RUN mkdir build
WORKDIR /uncrustify/uncrustify-uncrustify-0.82.0/build/
RUN cmake ..
RUN MAKEFLAGS="-j $(nproc)" make -s

RUN make install DESTDIR=/uncrustify

# assemble the final container by copying over the artifacts from separately build containers
FROM base AS devcontainer

LABEL org.opencontainers.image.source=https://github.com/pgiceberg/pgiceberg
LABEL org.opencontainers.image.description="Development container for the pgiceberg project"
LABEL org.opencontainers.image.licenses=Apache-2.0

RUN yes | sudo unminimize; test "${PIPESTATUS[1]}" -eq 0

# for persistent bash history across devcontainers we need to have
# a) a directory to store the history in
# b) a prompt command to append the history to the file
# c) specify the history file to store the history in
# b and c are done in the .bashrc to make it persistent across shells only
RUN sudo install -d -o iceberg -g iceberg /commandhistory \
 && echo "export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" >> "/home/iceberg/.bashrc"

COPY --link --from=uncrustify-builder /uncrustify/usr/ /usr/
COPY --link --from=pg18 /home/iceberg/.pgenv-staging/ /home/iceberg/.pgenv/

VOLUME /data
RUN sudo mkdir /data \
 && sudo chown iceberg:iceberg /data

# sets default pg version
RUN pgenv switch 18.4

ENV CC=/usr/bin/gcc-14
ENV CXX=/usr/bin/g++-14
ENV PGPORT=5432
